### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by kevintransp** [ZAUB1/ESX-Pizza#3]
Hello,
Like this script, could you tell me how to change the payments? i would like to have it lowered by 50%.

With kind regarts,

**Comment by lfuelling** [comment]
Hi,

for the tip, you can find this in `client.lua:172`.

The line you're looking for currently looks like this: `pourboire = math.random(100, 200)` and you can change 100 and 200 for your desired minimum and maximum. The actual payment will be radomized between those values. 

For your wish (50% reduction) you would have to change the values to 50 and 100. 

Additionally to this, there is a line in `client.lua:76`: `local coefflouze = 0.1 ` you can change that variable to change the final payout. For the 50% reduction, you'd have to change this to `0.05`.

Hope that helps.
